name: stacked_example_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.7
  injectable: ^1.0.4
  get_it: ^4.0.4
  stacked: ^1.7.6
  stacked_services: ^0.5.2
  flutter_hooks:
  stacked_hooks: ^0.1.1+3
  observable_ish:
  image_picker: ^0.6.7+4
  http:
  email_validator:



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.6.8
  injectable_generator: ^1.0.4


flutter:
  uses-material-design: true